name: hi_tech
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# required to store/read/edit/delete data locally
  path_provider: ^2.0.11
# to check the platform with browser compatibility
  universal_platform: ^0.1.3
# for international phone number input fields
  intl_phone_number_input: ^0.7.0+2
# for opening url intents
  url_launcher: ^6.1.5

  cupertino_icons: ^1.0.2

# localization manager for providing multi-language interface
  easy_localization: ^3.0.1
# Flutter widget that automatically resizes text to fit perfectly within its bounds.
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
  # translations
    - translations/
  #assets
    - assets/
